# Generated by Django 4.2.1 on 2023-07-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='verification',
            field=models.PositiveIntegerField(choices=[('Not verified', 0), ('Verified', 1)], default='0'),
        ),
    ]
