# Generated by Django 4.2.1 on 2023-07-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0002_alter_data_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='verification',
            field=models.PositiveIntegerField(choices=[(0, 'Not verified'), (1, 'Verified')], default='0'),
        ),
    ]
