# Generated by Django 4.2.1 on 2023-07-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0003_alter_data_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
