# Generated by Django 4.2.1 on 2023-07-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0005_alter_data_ssl_tls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='verification',
        ),
        migrations.AlterField(
            model_name='data',
            name='size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
