# Generated by Django 4.2.1 on 2023-08-05 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0006_remove_data_verification_alter_data_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Expiry_status',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Not Expired', 'Not Expired'), ('N/A', 'N/A')], default="Don't know", max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='ResponsiveOrNot',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default="Don't know", max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='SSL_TLS',
            field=models.CharField(choices=[('Enabled', 'Enabled'), ('Not Enabled', 'Not Enabled'), ('N/A', 'N/A')], default='NO', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='founded',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AlterField(
            model_name='data',
            name='industry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
